version: 2

models:
  - name: stg_addresses
    description: Delivery addresses 
    columns:
      - name: address_guid
        description: UUID for each unique address on platform
      - name: address 
        description: The first few lines of the address
      - name: zipcode
        description: zipcode of the address
      - name: state
        description: state this delivery address is based in
      - name: country
        description: country this delivery address is based in
        
  - name: stg_events
    description: Events that happen on the platform
    columns:
      - name: event_guid
        description: UUID of each unique event on the platform
      - name: session_guid
        description: UUID of each browsing session on the platform which can contain many events
      - name: user_guid
        description: UUID of the user that this event is associated with
      - name: page_url
        description: URL that the event happened on
      - name: created_at
        description: Timestamp of the event
      - name: event_type
        description: Type of event
      - name: order_guid
        description: If the event is specific to an order (mostly used for checkout)
      - name: product_guid
        description: If the event is specific to a product

  - name: stg_order_items
    description: Line items of each order 
    columns:
      - name: order_guid
        description: OrderId of this order
      - name: product_guid
        description: ProductId of a single item in this order 
      - name: quantity
        description: Number of units of the product in this order

  - name: stg_orders 
    description: Each order made by a customer 
    columns:
      - name: order_guid
        description: UUID for each unique order on platform
      - name: user_guid
        description: UserId of the user that placed this order
      - name: promo_guid
        description: PromoId if any was used in the order
      - name: address_guid
        description: Delivery address for this order
      - name: created_at
        description: timestamp when the order was created
      - name: order_cost
        description: Dollar about of the items in the order
      - name: shipping_cost
        description: Cost of shipping for the order
      - name: order_total
        description: Total cost of the order including shipping
      - name: tracking_id
        description: Tracking number for the order/package
      - name: shipping_service
        description: Company that was used for shipping
      - name: estimated_delivery_at
        description: Estimated date of delivery
      - name: delivered_at
        description: Actual timestamp of delivery
      - name: order_status
        description: Status of the order

  - name: stg_products
    description: Each product sold by greenery 
    columns:
      - name: product_guid
        description: UUID for each unique product on platform
      - name: name
        description: Name of the product
      - name: price
        description: Price of the product
      - name: inventory 
        description: Amount of the inventory we have for this product

  - name: stg_promos 
    description: Promo codes on the platform 
    columns:
      - name: promo_guid
        description: Each unique promocode on platform
      - name: discount
        description: Absolute dollar amount that is given off with the code
      - name: status 
        description: Is the promo code active or disabled

  - name: stg_superheroes 
    description: Contains information about superheroes
    columns:
      - name: id
        description: Id of the superhero in the database
      - name: name
        description: Name of the superhero
      - name: gender 
        description: Gender of the superhero
      - name: eye_color 
        description: Eyecolor of the superhero
      - name: race
        description: Race of the superhero
      - name: hair_color
        description: Hair color of the superhero
      - name: height
        description: height of the superhero
      - name: publisher
        description: publisher / comic brand that created the superhero
      - name: skin_color
        description: Skin color of the superhero
      - name: alignment
        description: Alignment of the superhero
      - name: weight
        description: Weight of the superhero
      - name: created_at
        description: timestamp the user was created
      - name: updated_at
        description: timestamp the user was last updated

  - name: stg_users 
    description: Contains information about users of Greenery application
    columns:
      - name: user_id
        description: UUID for each unique user on platform
      - name: first_name
        description: first name of the user
      - name: last_name 
        description: last name of the user
      - name: email 
        description: email address of the user
      - name: phone_number
        description: phone number of the user
      - name: created_at
        description: timestamp the user was created
      - name: updated_at
        description: timestamp the user was last updated
      - name: address_id
        description: default delivery address for the user