version: 2

sources:

  - name: postgres_source
    schema: public
    database: dbt

    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 5, period: day}
      error_after: {count: 7, period: day}
        
    tables:
      tables:
      - name: addresses
        description: >
          Contains address details of users
        columns:
          - name: address_id
          - name: address
          - name: zipcode
          - name: state
          - name: country

      - name: events
        loaded_at_field: created_at
        description: >
          Contains information about different actions done by users in the application
        columns:
          - name: event_id
          - name: session_id
          - name: user_id
          - name: page_url
          - name: created_at
          - name: event_type
          - name: order_id
          - name: product_id

      - name: order_items
        description: >
          Contains details of products bought for a given order
        columns:
          - name: order_id
          - name: product_id
          - name: quantity

      - name: orders
        loaded_at_field: created_at
        description: >
          Contains information about orders placed in the application
        columns:
          - name: order_id
          - name: user_id
          - name: promo_id
          - name: address_id
          - name: created_at
          - name: order_cost
          - name: shipping_cost
          - name: order_total
          - name: tracking_id
          - name: shipping_service
          - name: estimated_delivery_at
          - name: delivered_at
          - name: status

      - name: products
        description: >
          Contains information about product offered
        columns:
          - name: product_id
          - name: name
          - name: price
          - name: inventory

      - name: promos
        description: >
          Contains information about different kind promotion offered in the application
        columns:
          - name: promo_id
          - name: discount
          - name: status

      - name: superheroes
        description: >
          Contains information about superheroes
        columns:
          - name: id
          - name: name
          - name: gender
          - name: eye_color
          - name: race
          - name: hair_color
          - name: height
          - name: publisher
          - name: skin_color
          - name: alignment
          - name: weight
          - name: created_at
          - name: updated_at

      - name: users
        description: >
          Contains information about users of Greenery application
        columns:
          - name: user_id
          - name: first_name
          - name: last_name
          - name: email
          - name: phone_number
          - name: created_at
          - name: updated_at
          - name: address_id