version: 2

sources:

  - name: postgres_source
    schema: public
    database: dbt

    quoting:
      database: false
      schema: false
      identifier: false

    freshness:
      warn_after: {count: 5, period: day}
      error_after: {count: 7, period: day}
        
    tables:
      - name: addresses
        description: >
          Contains address details of users

      - name: events
        loaded_at_field: created_at
        description: >
          Contains information about different actions done by users in the application

      - name: order_items
        description: >
          Contains details of products bought for a given order

      - name: orders
        loaded_at_field: created_at
        description: >
          Contains information about orders placed in the application

      - name: products
        description: >
          Contains information about product offered

      - name: promos
        description: >
          Contains information about different kind promotion offered in the application

      - name: superheroes
        description: >
          Contains information about superheroes

      - name: users
        description: >
          Contains information about users of Greenery application