version: 2

models:
  - name: stg_addresses
    description: Delivery addresses 
    columns:
      - name: address_guid
        description: UUID for each unique address on platform
        tests:
          - not_null
          - unique
      - name: address 
        description: The first few lines of the address
      - name: zipcode
        description: zipcode of the address
        tests:
          - not_null
      - name: state
        description: state this delivery address is based in
      - name: country
        description: country this delivery address is based in
        
  - name: stg_events
    description: Events that happen on the platform
    columns:
      - name: event_guid
        description: UUID of each unique event on the platform
        tests:
          - not_null
          - unique
      - name: session_guid
        description: UUID of each browsing session on the platform which can contain many events
        tests:
          - not_null
      - name: user_guid
        description: UUID of the user that this event is associated with
        tests:
          - not_null
          - relationships:
              to: ref('stg_users')
              field: user_guid
      - name: page_url
        description: URL that the event happened on
        tests:
          - not_null
      - name: created_at
        description: Timestamp of the event
      - name: event_type
        description: Type of event
        tests:
          - not_null
          - accepted_values:
              values: ["add_to_cart", "checkout", "page_view","package_shipped"]
      - name: order_guid
        description: If the event is specific to an order (mostly used for checkout)
        tests:
          - not_null:
              config:
                where: "event_type IN ('checkout', 'package_shpped')"
      - name: product_guid
        description: If the event is specific to a product
        tests:
        - not_null:
              config:
                where: "event_type IN ('add_to_cart', 'page_view')"

  - name: stg_order_items
    description: Line items of each order 
    columns:
      - name: order_guid
        description: OrderId of this order
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_guid
      - name: product_guid
        description: ProductId of a single item in this order
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_guid 
      - name: quantity
        description: Number of units of the product in this order
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"

  - name: stg_orders 
    description: Each order made by a customer 
    columns:
      - name: order_guid
        description: UUID for each unique order on platform
        tests:
          - not_null
          - unique
      - name: user_guid
        description: UserId of the user that placed this order
        tests:
          - not_null
      - name: promo_guid
        description: PromoId if any was used in the order
        tests:
          - relationships:
              to: ref('stg_promos')
              field: promo_guid
      - name: address_guid
        description: Delivery address for this order
        tests:
          - not_null
          - relationships:
              to: ref('stg_addresses')
              field: address_guid
      - name: created_at
        description: timestamp when the order was created
        tests:
          - not_null
      - name: order_cost
        description: Dollar about of the items in the order
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"
      - name: shipping_cost
        description: Cost of shipping for the order
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"
      - name: order_total
        description: Total cost of the order including shipping
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"
      - name: tracking_guid
        description: Tracking number for the order/package
        tests:
          - not_null:
              config:
                where: "order_status IN ('shipped', 'delivered')"
      - name: shipping_service
        description: Company that was used for shipping
        tests:
          - not_null:
              config:
                where: "order_status IN ('shipped', 'delivered')"
      - name: estimated_delivery_at
        description: Estimated date of delivery
      - name: delivered_at
        description: Actual timestamp of delivery
        tests:
          - not_null:
              config:
                where: "order_status IN ('delivered')"
      - name: order_status
        description: Status of the order
        tests:
          - not_null
          - accepted_values:
              values: ['preparing', 'shipped', 'delivered']

  - name: stg_products
    description: Each product sold by greenery 
    columns:
      - name: product_guid
        description: UUID for each unique product on platform
        tests:
          - not_null
          - unique
      - name: name
        description: Name of the product
        tests:
          - not_null
          - unique
      - name: price
        description: Price of the product
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"
      - name: inventory 
        description: Amount of the inventory we have for this product
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"

  - name: stg_promos 
    description: Promo codes on the platform 
    columns:
      - name: promo_guid
        description: Each unique promocode on platform
        tests:
          - not_null
          - unique
      - name: discount
        description: Absolute dollar amount that is given off with the code
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0 AND discount < 100"
      - name: status 
        description: Is the promo code active or disabled
        tests:
          - not_null
          - accepted_values:
              values: ['active', 'inactive']

  - name: stg_superheroes 
    description: Contains information about superheroes
    columns:
      - name: id
        description: Id of the superhero in the database
      - name: name
        description: Name of the superhero
      - name: gender 
        description: Gender of the superhero
      - name: eye_color 
        description: Eyecolor of the superhero
      - name: race
        description: Race of the superhero
      - name: hair_color
        description: Hair color of the superhero
      - name: height
        description: height of the superhero
      - name: publisher
        description: publisher / comic brand that created the superhero
      - name: skin_color
        description: Skin color of the superhero
      - name: alignment
        description: Alignment of the superhero
      - name: weight
        description: Weight of the superhero
      - name: created_at
        description: timestamp the user was created
      - name: updated_at
        description: timestamp the user was last updated

  - name: stg_users 
    description: Contains information about users of Greenery application
    columns:
      - name: user_guid
        description: UUID for each unique user on platform
        tests:
          - not_null
          - unique
      - name: first_name
        description: first name of the user
        tests:
          - not_null
      - name: last_name 
        description: last name of the user
        tests:
          - not_null
      - name: email 
        description: email address of the user
        tests:
          - not_null
      - name: phone_number
        description: phone number of the user
        tests:
          - not_null
      - name: created_at
        description: timestamp the user was created
        tests:
          - not_null
      - name: updated_at
        description: timestamp the user was last updated
      - name: address_guid
        description: default delivery address for the user
        tests:
          - relationships:
              to: ref('stg_addresses')
              field: address_guid