version: 2

models:
  - name: dim_products
    description: Each product sold by greenery 
    columns:
      - name: product_guid
        description: UUID for each unique product on platform
        tests:
          - not_null
          - unique
      - name: name
        description: Name of the product
        tests:
          - not_null
          - unique
      - name: unit_price
        description: Price of the product
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"
      - name: current_inventory
        description: Amount of the inventory we have for this product
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " > 0"
      - name: total_product_bought
        description: Total units bought overall
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: " >= 0"

  - name: product_events_facts
    description: Has product level session metrics on different events
    tests:
      - dbt_utils.expression_is_true:
          expression: "last_event_time >= first_event_time"
    columns:
      - name: session_guid
        description: UUID of each browsing session on the platform which can contain many events
        tests:
          - not_null
      - name: product_guid
        description: UUID of the product that this event is associated with
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_guid
      - name: page_view
        description: Number of page views in the session
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
      - name: add_to_cart
        description: Number of add to cart actions in the session
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
      - name: package_shipped
        description: Number of package shipped actions in the session
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
      - name: checkout
        description: Number of checkout actions in the session
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0 
      - name: first_event_time
        description: Session begin time
        tests:
          - not_null
      - name: last_event_time
        description: Session end time
        tests:
          - not_null
      - name: total_time_elapsed_mins
        description: Total time of the session
        tests:
          - not_null

  - name: conversion_rate_details
    description: Has overall and product conversion rates
    columns:
      - name: product_name
        description: Name of the product 
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: name
      - name: product_conversion_rate
        description: Conversion rate of product
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 100
      - name: overall_conversion_rate
        description: Overall conversion rate
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0  
              max_value: 100